services:
  db:
    image: postgres:15
    container_name: afterbuy-mirakl-db
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      # значения берутся из .env, здесь оставлены дефолты для ясности
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - "8303:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: afterbuy-mirakl-backend
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    command: ["/bin/sh", "/app/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - app-network

  extrup-admin:
    build:
      context: ./extrup-admin
      dockerfile: Dockerfile
    container_name: afterbuy-mirakl-frontend
    depends_on:
      - backend
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: afterbuy-mirakl-nginx
    ports:
      - "8180:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - extrup-admin
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
