"""market: xl/jv

Revision ID: 3c3881ad34a4
Revises: c587f05c125a
Create Date: 2025-10-08 10:14:07.239344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3881ad34a4'
down_revision: Union[str, Sequence[str], None] = 'c587f05c125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_fabrics', sa.Column('market', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_fabrics', 'market')
    # ### end Alembic commands ###
