"""shop destination - vente or xxxlutz default value

Revision ID: adedce1f187b
Revises: 3c3881ad34a4
Create Date: 2025-10-09 09:58:34.863360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adedce1f187b'
down_revision: Union[str, Sequence[str], None] = '3c3881ad34a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable with default value
    op.add_column('uploaded_fabrics', sa.Column('shop', sa.String(), nullable=True, default='vente'))
    
    # Update existing rows with default value
    op.execute("UPDATE uploaded_fabrics SET shop = 'vente' WHERE shop IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('uploaded_fabrics', 'shop', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_fabrics', 'shop')
    # ### end Alembic commands ###
