"""fixed fabric table/created ean table

Revision ID: c587f05c125a
Revises: c8183f77e2f2
Create Date: 2025-10-02 13:19:17.538340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c587f05c125a'
down_revision: Union[str, Sequence[str], None] = 'c8183f77e2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afterbuy_fabric_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_fabrics_id'), 'uploaded_fabrics', ['id'], unique=False)
    op.add_column('uploaded_eans', sa.Column('uploaded_fabric_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploaded_eans', 'uploaded_fabrics', ['uploaded_fabric_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_eans', type_='foreignkey')
    op.drop_column('uploaded_eans', 'uploaded_fabric_id')
    op.drop_index(op.f('ix_uploaded_fabrics_id'), table_name='uploaded_fabrics')
    op.drop_table('uploaded_fabrics')
    # ### end Alembic commands ###
