"""create uploaded_eans tables

Revision ID: c8183f77e2f2
Revises: 90526adb3f7a
Create Date: 2025-10-01 18:06:14.781449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8183f77e2f2'
down_revision: Union[str, Sequence[str], None] = '90526adb3f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_eans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('afterbuy_fabric_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_1', sa.String(), nullable=False),
    sa.Column('image_2', sa.String(), nullable=False),
    sa.Column('image_3', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_eans_ean'), 'uploaded_eans', ['ean'], unique=False)
    op.create_index(op.f('ix_uploaded_eans_id'), 'uploaded_eans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_eans_id'), table_name='uploaded_eans')
    op.drop_index(op.f('ix_uploaded_eans_ean'), table_name='uploaded_eans')
    op.drop_table('uploaded_eans')
    # ### end Alembic commands ###
